version: '3.5'
services:
  backend:
    image: backend
    build:
      dockerfile: Dockerfile
      context: ./backend
  proxy:
    image: nginx:alpine
    depends_on:
      - backend
    ports:
      - 80:81
    volumes:
      - type: bind
        source: ./proxy/nginx-proxy.conf
        target: /etc/nginx/conf.d/proxy.conf
      - type: bind
        source: ./proxy/app.crt
        target: /etc/ssl/certs/app.crt
      - type: bind
        source: ./proxy/app.key
        target: /etc/ssl/private/app.key